// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace OOP_pr_8_2
{
    public partial class WindowController : NSWindowController
    {

        public TV tv;


        public WindowController(IntPtr handle) : base(handle)
        {

        }


        partial void AddBtn(NSObject sender)
        {

            tv.cost = int.Parse(CostField.StringValue);
            tv.diagonal = int.Parse(DiagonalField.StringValue);
            tv.model = ModelField.StringValue;
            tv.screen_resolution = ScreenField.StringValue;
            tv.country = CountryField.StringValue;
            tv.channel = ChannelField.StringValue;
            Console.WriteLine("aaaaaaaaaa");

        }
    }

}
